시작 페이지 구현
s-center/kiosk pull request #2
Opened 2023-08-30 08:14 UTC by ENvironmentSet

프로젝트 설정을 수정하고 피그마의 1번, 2번 페이지를 부분적으로 구현했습니다.

## 프로젝트 설정 변경점

- 오버엔지니어링이라 생각해 `storybook`과 `react-spring`을 제거했습니다.
- 초기 설정 시 스타터 코드에서 미처 제거하지 못한 것으로 보이는 `prop-types`를 제거했습니다.
- 모든 플랫폼에서의 일관적인 개발 경험을 위해 [CSS reset](http://meyerweb.com/eric/tools/css/reset/) 을 적용했습니다.
- `wouter`로 클라이언트 사이드 라우팅을 세팅했습니다.
- `ViewBox` 컴포넌트를 만들어 최대한 키오스크와 비슷한 화면비의 화면에서 작업할 수 있도록 설정했습니다.
- emotion의 `css` prop을 사용하기 위해 eslint 설정을 변경했습니다.
- `prop-types`를 삭제하며 관련 eslint 검사를 진행하지 않도록 설정했습니다.
  
## 페이지 구현 사항

피그마의 1번, 2번 페이지를 `Starting`이라는 이름의 페이지(`/starting`)로 구현했습니다. 각 에셋과 컴포넌트들의 비율이 원 디자인과 조금 상이하나, 추후 디자인 팀으로부터 정확한 비율을 전달받으면 수정할 예정입니다.

2023-08-31 03:58 UTC, ENvironmentSet commented
여담이지만 PR은 이것보다 더 잘게 쪼게는 게 좋습니다. 각각이 독립적인 패치로 기능하게끔요. 이 PR 같은 경우에는 '프로젝트 설정 변경'과 '시작 페이지 구현' 두 개로 나누는 게 정석이긴 합니다.

2023-09-01 02:53 UTC, kong33 requested changes
수정 부탁드립니다!

2023-09-01 02:53 UTC, kong33 commented on src/pages/Starting/index.jsx
> +  const reaction = transformation => css`
잘못된 추상화 같아요!

2023-09-02 03:28 UTC, ENvironmentSet commented on index.html
>      <title>scenter kiosk</title>
브랜드 이름이 제대로 정해지지 않았을 때 임시로 설정했었는데 이제 이름이 정해졌으니 변경해야 할 거 같습니다.

2023-09-02 06:01 UTC, kong33 commented on index.html
>      <title>scenter kiosk</title>
넵 . heavenly cocktail 로 바꾸면 될 것 같습니다. 재원님이 바꾸실건가요?

2023-09-02 06:25 UTC, ENvironmentSet commented
- 홑따옴표 사용을 강제하는 eslint 규칙을 추가했습니다.
- 세미콜론 사용을 금지하는 eslint 규칙을 추가했습니다.

2023-09-02 06:25 UTC, ENvironmentSet commented on index.html
>      <title>scenter kiosk</title>
네, 제가 다른 pr로 올릴게요.

2023-09-02 06:27 UTC, merged